# Generated by Django 3.1.3 on 2020-11-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsImage',
        ),
    ]
