# Generated by Django 3.1.3 on 2020-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201128_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=0, verbose_name='Количество на складе'),
            preserve_default=False,
        ),
    ]
