# Generated by Django 3.1.3 on 2020-11-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_path', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uid',
            name='uid',
            field=models.CharField(max_length=25, verbose_name='Юид'),
        ),
        migrations.AlterField(
            model_name='uid',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец юида'),
        ),
    ]
