# Generated by Django 3.1.3 on 2020-11-26 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20201126_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=60, verbose_name='Адресс пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_detail',
            field=models.CharField(blank=True, max_length=60, verbose_name='Детали связанные с банком'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='Является ли магазином'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='Юридический адресс магазина'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Телефон пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unp',
            field=models.CharField(blank=True, max_length=60, verbose_name='Унп магазина'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновление пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь профиля'),
        ),
    ]
